"""Compute the PWM-PET-IQ Technical-Validation tables from extracted ROI means.

Consumes a ``roi_means.json`` (produced by ``extract_roi_means.py`` from the reconstructed
volumes) and emits, per count level and sphere: percent contrast recovery (CRC), background
variability, and CNR -- plus the decayed-vs-thinned Bland-Altman agreement that is the
dataset's central validation. All arithmetic goes through ``nema_metrics`` (unit-tested).

roi_means.json contract:
{
  "true_activity_ratio": 4.0,
  "levels": {
    "<level_id>": {
      "origin": "reference|decayed|thinned",
      "count_level": 1.0,
      "spheres":     {"10": {"c_hot": <mean>, "kind": "hot"}, ...},
      "bg_roi_means": {"10": [<12x5 background ROI means>], ...}
    }, ...
  }
}

Usage:
    python analyze_phantom.py --roi-means roi_means.json --out tables
"""
from __future__ import annotations

import argparse
import json
import os
from typing import Any, Dict, List

from nema_metrics import (background_variability, bland_altman, contrast_to_noise,
                          percent_contrast_cold, percent_contrast_hot)


def level_metrics(level: Dict[str, Any], true_ratio: float) -> Dict[str, Dict[str, float]]:
    out: Dict[str, Dict[str, float]] = {}
    for size, sph in level["spheres"].items():
        bg = level["bg_roi_means"][size]
        c_bg = sum(bg) / len(bg)
        if sph.get("kind", "hot") == "cold":
            crc = percent_contrast_cold(sph["c_hot"], c_bg)
        else:
            crc = percent_contrast_hot(sph["c_hot"], c_bg, true_ratio)
        out[size] = {
            "crc_percent": crc,
            "background_variability_percent": background_variability(bg),
            "cnr": contrast_to_noise(sph["c_hot"], c_bg, bg),
        }
    return out


def compute_all(doc: Dict[str, Any]) -> Dict[str, Any]:
    tr = doc["true_activity_ratio"]
    per_level = {lid: level_metrics(lv, tr) for lid, lv in doc["levels"].items()}
    return {"true_activity_ratio": tr, "per_level": per_level}


def decayed_vs_thinned(per_level: Dict[str, Any], decayed_id: str, thinned_id: str) -> Dict[str, Any]:
    """Bland-Altman of per-sphere CRC between a decayed and a matched thinned level."""
    a, b = per_level[decayed_id], per_level[thinned_id]
    sizes = sorted(set(a) & set(b), key=int)
    x = [a[s]["crc_percent"] for s in sizes]
    y = [b[s]["crc_percent"] for s in sizes]
    return {"decayed": decayed_id, "thinned": thinned_id, "sphere_mm": sizes,
            "crc_bland_altman": bland_altman(x, y)}


def to_latex(res: Dict[str, Any]) -> str:
    lines = ["% auto-generated by analyze_phantom.py -- do not hand-edit",
             "\\textbf{Level} & \\textbf{Sphere (mm)} & \\textbf{CRC (\\%)} "
             "& \\textbf{Bkg var. (\\%)} & \\textbf{CNR} \\\\", "\\midrule"]
    for lid in sorted(res["per_level"]):
        for size in sorted(res["per_level"][lid], key=int):
            m = res["per_level"][lid][size]
            lines.append(f"{lid} & {size} & {m['crc_percent']:.1f} & "
                         f"{m['background_variability_percent']:.1f} & {m['cnr']:.2f} \\\\")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--roi-means", required=True)
    ap.add_argument("--out", default="tables")
    args = ap.parse_args()
    with open(args.roi_means, encoding="utf-8") as fh:
        doc = json.load(fh)
    res = compute_all(doc)
    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, "image_quality.json"), "w", encoding="utf-8") as fh:
        json.dump(res, fh, indent=2, sort_keys=True)
    with open(os.path.join(args.out, "image_quality.tex"), "w", encoding="utf-8") as fh:
        fh.write(to_latex(res))
    print(f"image quality: {len(res['per_level'])} levels analyzed -> {args.out}/")


if __name__ == "__main__":
    main()
